#ifndef RLPBR_VK_COMP_DEFINITIONS_H_INCLUDED
#define RLPBR_VK_COMP_DEFINITIONS_H_INCLUDED

#define WORKGROUP_SIZE (256)
#define LOCAL_WORKGROUP_X (16)
#define LOCAL_WORKGROUP_Y (16)
#define LOCAL_WORKGROUP_Z (1)

#endif
